import Head from "next/head";
// import styles from "../styles/Home.module.css";
import * as PushAPI from "@pushprotocol/restapi";
import * as ethers from "ethers";

export default function Home() {
  const PK = process.env.NEXT_PUBLIC_PRIVATE; // channel private key
  // console.log("my pk is : ", PK);
  const Pkey = `0x${PK}`;
  const signer = new ethers.Wallet(Pkey);

  const sendNotificationBhejo = async () => {
    try {
      const apiResponse = await PushAPI.payloads.sendNotification({
        signer,
        type: 3, // target
        identityType: 2, // direct payload
        notification: {
          title: `[SDK-TEST] notification TITLE:`,
          body: `[sdk-test] notification BODY`,
        },
        payload: {
          title: `Deepu ka haal chaal`,
          body: `notification ja raha hai`,
          cta: "",
          img: "",
        },
        recipients: "eip155:5:0xFe20f562482c33d1447947ef67bb20A3cb98C2ae", // recipient address
        channel: "eip155:5:0x67099d557997E3Ee308B3C49029C331A2d4569Dc", // your channel address
        env: "staging",
      });

      // apiResponse?.status === 204, if sent successfully!
      console.log("API repsonse: ", apiResponse);
    } catch (err) {
      console.error("Error: ", err);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button
          onClick={sendNotificationBhejo}
          style={{
            height: "60px",
            borderRadius: "20px",
            fontSize: "30px",
            color: "blue",
            cursor: "pointer",
          }}
        >
          sent notification
        </button>
      </div>
    </>
  );
}
